services:
    redis:
        image: redis:alpine
        restart: always
        ports:
            - 6379:6379

    postgres:
        image: postgres:14-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=music_box_dev
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        restart: always
